import type { CAC } from "cac";
import fs from "node:fs";

export const checkDeprecatedIconFilesCommand = (cli: CAC) => {
  cli
    .command("check-deprecated-icon-files [path]", "Check deprecated icon files")
    .action(async (path) => {
      const files = fs.readdirSync(path, { recursive: true });

      const deprecatedIconFileNames = deprecatedIconNames.flatMap((name) => {
        const nameTrimmed = name.replace("icon_", "");

        return [
          // icon_arrow_downward
          name,
          // arrow_downward
          nameTrimmed,
          // icon-arrow-downward
          name.replace(/_/g, "-"),
          // iconarrowdownward
          name.replace(/_/g, ""),
          // iconarrowdownwardthin
          `${name.replace(/_/g, "")}thin`,
          // iconarrowdownwardregular
          `${name.replace(/_/g, "")}regular`,
          // iconarrowdownwardfill
          `${name.replace(/_/g, "")}fill`,
          // arrow-downward
          nameTrimmed.replace(/_/g, "-"),
          // arrowdownward
          nameTrimmed.replace(/_/g, ""),
          // arrowdownwardthin
          `${nameTrimmed.replace(/_/g, "")}thin`,
          // arrowdownwardregular
          `${nameTrimmed.replace(/_/g, "")}regular`,
          // arrowdownwardfill
          `${nameTrimmed.replace(/_/g, "")}fill`,
        ];
      });

      for (const file of files) {
        if (typeof file !== "string") continue;
        if (file.includes("node_modules/")) continue;

        const fileNameLowered = file.split("/").pop().split(".")[0].toLowerCase();
        if (extensionsToCheck.every((ext) => file.endsWith(ext) === false)) continue;

        if (deprecatedIconFileNames.includes(fileNameLowered)) {
          console.log(`Possible deprecated icon file found: ${file}`);
        }
      }
    });
};

const extensionsToCheck = [".tsx", ".jsx", ".svg", ".png"];

const deprecatedIconNames = [
  "icon_add",
  "icon_add_circle",
  "icon_aeb",
  "icon_ai",
  "icon_android_share",
  "icon_arrow",
  "icon_arrow_downward",
  "icon_arrow_drop_down",
  "icon_arrow_drop_up",
  "icon_arrow_upward",
  "icon_article",
  "icon_backward",
  "icon_bill",
  "icon_bold",
  "icon_bookmark",
  "icon_bookmark_list",
  "icon_calendar",
  "icon_call",
  "icon_call_declined",
  "icon_camera",
  "icon_car",
  "icon_car_around_view",
  "icon_car_blind_spot",
  "icon_car_cruise_control",
  "icon_car_epb",
  "icon_car_heated_seat",
  "icon_car_heated_steering_wheel",
  "icon_car_ldws",
  "icon_car_leather_seat",
  "icon_car_navigation",
  "icon_car_power_trunk",
  "icon_car_rear_camera",
  "icon_car_rear_sensor",
  "icon_car_smart_key",
  "icon_car_ventilation_seat",
  "icon_cart",
  "icon_certification",
  "icon_challenge",
  "icon_chart",
  "icon_chat_bubble_check",
  "icon_chatting",
  "icon_chatting_send",
  "icon_check",
  "icon_check_flower",
  "icon_chevron_left",
  "icon_chevron_right",
  "icon_click",
  "icon_clock",
  "icon_close",
  "icon_cobuying",
  "icon_community",
  "icon_condo",
  "icon_confirmation",
  "icon_confirmation_pay",
  "icon_confirmation_profile",
  "icon_contents",
  "icon_convert",
  "icon_copy",
  "icon_coupon",
  "icon_coupon_download_done",
  "icon_coupon_used",
  "icon_delete_keyboard",
  "icon_delivery",
  "icon_direction",
  "icon_download",
  "icon_edit",
  "icon_emoticon",
  "icon_emoticon_bad",
  "icon_expand",
  "icon_expand_less",
  "icon_expand_more",
  "icon_file",
  "icon_filter02",
  "icon_forward",
  "icon_gender",
  "icon_global",
  "icon_gps",
  "icon_gps_enable",
  "icon_gps_enable2",
  "icon_groupchat_king",
  "icon_handle",
  "icon_hashtag",
  "icon_headphone",
  "icon_heart",
  "icon_help",
  "icon_helpcenter",
  "icon_helper",
  "icon_home",
  "icon_house",
  "icon_housekeeping_book",
  "icon_import",
  "icon_info",
  "icon_interest",
  "icon_interest_list",
  "icon_invite",
  "icon_invite_friend",
  "icon_ios_share",
  "icon_jobs",
  "icon_keyboard_hiding",
  "icon_keyword",
  "icon_laptop",
  "icon_leaf",
  "icon_list",
  "icon_list_card",
  "icon_list_check",
  "icon_list_select",
  "icon_list_thumbnail",
  "icon_location",
  "icon_lock",
  "icon_loudspeaker",
  "icon_map",
  "icon_market",
  "icon_market_check",
  "icon_market_write",
  "icon_mention",
  "icon_menu",
  "icon_mic",
  "icon_mic_off",
  "icon_mission",
  "icon_mobile",
  "icon_money_send",
  "icon_money_won",
  "icon_moon",
  "icon_more_horiz",
  "icon_more_vert",
  "icon_my",
  "icon_my_profile",
  "icon_near_me",
  "icon_newtopic",
  "icon_note",
  "icon_notification",
  "icon_notification_fall",
  "icon_notification_off",
  "icon_order",
  "icon_pause",
  "icon_payment",
  "icon_percent",
  "icon_photo",
  "icon_photo_edit",
  "icon_photo_edit_crop",
  "icon_photo_edit_draw",
  "icon_photo_edit_rotate",
  "icon_photo_several",
  "icon_play",
  "icon_poll",
  "icon_price_won",
  "icon_product",
  "icon_profile",
  "icon_profile_badge",
  "icon_prohibition",
  "icon_pushpin",
  "icon_question_check",
  "icon_redo",
  "icon_refund",
  "icon_remove_circle",
  "icon_reply",
  "icon_reply_mission",
  "icon_reply_re",
  "icon_report",
  "icon_reservation",
  "icon_restaurant",
  "icon_retry",
  "icon_review_star",
  "icon_scanner",
  "icon_search",
  "icon_search_doc",
  "icon_sell",
  "icon_setting",
  "icon_signout",
  "icon_sort",
  "icon_story",
  "icon_story_article",
  "icon_subtract_circle",
  "icon_subtraction",
  "icon_suggest",
  "icon_sun",
  "icon_talkingdown",
  "icon_talkingup",
  "icon_text",
  "icon_thumb_down",
  "icon_thumb_up",
  "icon_toolbox",
  "icon_translate",
  "icon_trash",
  "icon_undo",
  "icon_user_group",
  "icon_video",
  "icon_view_count",
  "icon_view_count_off",
  "icon_volume_off",
  "icon_volume_on",
  "icon_vote",
  "icon_voucher",
  "icon_walk",
  "icon_warning",
  "icon_write",
  "icon_write_frequent_use",
  "icon_write_story",
];
