yarnPath: ".yarn/releases/yarn-berry.cjs"

npmScopes:
  daangn:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmPublishRegistry: "https://npm.pkg.github.com"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${GITHUB_TOKEN}"

packageExtensions:
  "istanbul-lib-processinfo@*":
    dependencies:
      "mkdirp": "*"
  "tcompare@*":
    dependencies:
      "diff": "*"
  "treport@*":
    dependencies:
      "tap-yaml": "*"
