enableImmutableInstalls: false

nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  istanbul-lib-processinfo@*:
    dependencies:
      mkdirp: "*"
  tcompare@*:
    dependencies:
      diff: "*"
  treport@*:
    dependencies:
      tap-yaml: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
