compressionLevel: mixed

enableGlobalCache: false

nmMode: hardlinks-global

nodeLinker: node-modules

npmScopes:
  daangn:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com/"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
