export {
  TabsContent as Content,
  TabsIndicator as Indicator,
  TabsList as List,
  TabsRoot as Root,
  TabsCarouselCamera as CarouselCamera,
  TabsCarousel as Carousel,
  TabsTrigger as Trigger,
  TabsTriggerLabel as TriggerLabel,
  TabsTriggerNotification as TriggerNotification,
  type TabsContentProps as ContentProps,
  type TabsIndicatorProps as IndicatorProps,
  type TabsListProps as ListProps,
  type TabsRootProps as RootProps,
  type TabsCarouselCameraProps as CarouselCameraProps,
  type TabsCarouselProps as CarouselProps,
  type TabsTriggerLabelProps as TriggerLabelProps,
  type TabsTriggerNotificationProps as TriggerNotificationProps,
  type TabsTriggerProps as TriggerProps,
} from "./Tabs";
