on:
  push:
    branches:
      - "**"
      - "!main"
    paths:
      - "docs/**"
      - "packages/recipe/**"
      - "packages/stylesheet/**"
      - "packages/react/**"
      - "packages/stackflow/**"
      - ".github/workflows/deploy-alpha-pages.yml"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN }}

name: Deploy seed-design-v3 docs (Alpha)

jobs:
  deploy:
    name: Deploy Seed Design V3 Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build Packages
        run: yarn build-only-package && yarn rootage:build

      - name: Build Docs
        working-directory: ./docs
        run: |
          yarn add vercel@35.0.0 && yarn pages:build

      - name: Deploy docs at Cloudflare Pages in `seed-design-v3` project (Alpha)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: ./docs
          command: pages deploy .vercel/output/static --project-name=seed-design-v3 --branch=${{ github.ref_name }}
        env:
          SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN }}
