on:
  push:
    branches:
      - main
      - dev # V3 deployment; remove this when V3 is stable
    paths:
      - "examples/stackflow-spa/**"
      - "packages/recipe/**"
      - "packages/stylesheet/**"
      - "packages/react/**"
      - "packages/stackflow/**"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Deploy seed-design-v3 QA app

jobs:
  deploy:
    name: Deploy Seed Design V3 QA app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build Packages
        run: bun build-only-package

      - name: Build QA app
        working-directory: ./examples/stackflow-spa
        run: |
          bun run build

      - name: Deploy qa app at Cloudflare Pages in `seed-design-qa` project
        run: |
          CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} \
          CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} \
          bun wrangler pages deploy ./examples/stackflow-spa/dist --project-name=seed-design-qa --branch=${{ github.ref_name }}
