on:
  push:
    branches:
      - '**'
    paths:
      - 'docs/content/component/**/component-meta.json'
      - 'docs/content/primitive/**/primitive-meta.json'

name: Validate Seed Docs meta json files

jobs:
  build:
    name: Validate meta json files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18.12.1
        cache: yarn
    
    - name: Install Dependencies
      run: yarn install --immutable

    - name: Validate meta json files
      working-directory: ./docs
      run: |
        yarn validate:meta-json

    - name: Report success
      run: echo "Script ran successfully!"
