on: 
  pull_request:
    types: 
      - opened
    paths:
      - 'docs/**'

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    name: Comment in docs PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Deploy Seed Docs Alpha Pages / Deploy Seed Docs (push) CI가 성공적으로 끝나면 해당 링크로 이동해서 preview를 확인해요 -> https://dash.cloudflare.com/aad5c82543cd1f267b89737d0f56405e/pages/view/seed-design
