on:
  push:
    branches:
      - "**"
      - "!main"
      - "!dev" # V3 deployment; remove this when V3 is stable
    paths:
      - "docs/**"
      - "packages/recipe/**"
      - "packages/stylesheet/**"
      - "packages/react/**"
      - "packages/stackflow/**"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Deploy seed-design-v3 docs (Alpha)

jobs:
  deploy:
    name: Deploy Seed Design V3 Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            docs/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build Packages
        run: bun build-only-package && bun rootage:build

      - name: Build Docs
        working-directory: ./docs
        run: |
          bun run build

      - name: Deploy docs at Cloudflare Pages in `seed-design-v3` project (Alpha)
        run: |
          CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} \
          CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} \
          bun wrangler pages deploy ./docs/out --project-name=seed-design-v3 --branch=${{ github.ref_name }}
