on:
  push:
    branches:
      - '**'
      - '!main'

    paths:
      - 'docs/**'

name: Deploy Seed Docs Alpha Pages

jobs:
  deploy:
    name: Deploy Seed Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: yarn
      
      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build `seed-design/design-token`
        working-directory: ./packages/design-token
        run: |
          yarn build

      - name: Build `seed-design/design-theming`
        working-directory: ./packages/react-theming
        run: |
          yarn build

      - name: Cache Gatsby `.cache` Folder
        uses: actions/cache@v3
        id: gatsby-cache-folder
        with:
          path: docs/.cache
          key: ${{ runner.os }}-cache-gatsby
          restore-keys: |
            ${{ runner.os }}-cache-gatsby

      - name: Cache Gatsby `public` Folder
        uses: actions/cache@v3
        id: gatsby-public-folder
        with:
          path: docs/public/
          key: ${{ runner.os }}-public-gatsby
          restore-keys: |
            ${{ runner.os }}-public-gatsby

      - name: Seed Docs를 빌드해요
        working-directory: ./docs
        run: |
          yarn build
        env:
          # incremental builds
          # https://www.gatsbyjs.org/docs/page-build-optimizations-for-incremental-data-changes/
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
      
      - name: 서비스를 Cloudflare pages에 배포해요
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages publish ./docs/public --project-name=seed-design --branch=${{ github.ref_name }}
