on:
  push:
    branches:
      - "**"
      - "!main"

    paths:
      - "docs/**"
      - "packages/recipe/**"
      - "packages/stylesheet/**"
      - "packages/react/**"
      - "packages/stackflow/**"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Deploy seed-design-v3 Storybook Alpha

jobs:
  deploy:
    name: Deploy seed-design-v3 Storybook Alpha
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --immutable

      - name: Build Packages
        run: bun build-only-package

      - name: Build Storybook
        working-directory: ./docs
        run: bun build-storybook

      - name: Deploy docs at Cloudflare Pages in `seed-design-v3-storybook` project (Alpha)
        run: |
          CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} \
          CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} \
          bun wrangler pages deploy ./docs/storybook-static --project-name=seed-design-v3-storybook --branch=${{ github.ref_name }}
