name: Test React Headless

on:
  push:
    paths:
      - "packages/react-headless/**/*"
      - ".github/workflows/react-headless-test.yml"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build headless common dependencies
        run: bun --filter @seed-design/dom-utils build && bun --filter @seed-design/react-primitive build

      - name: Run tests
        run: bun headless:test
